#!/usr/bin/env bash
# tick.sh — the SINGLE roadmap-completion gate. The ONLY path that flips "- [ ]" → "- [x]".
#
# Called by scripts/autopilot.sh (headless) AND the in-session /wrap flow, so that NO command,
# prompt, or model instruction can mark roadmap work complete without passing the SAME checks.
# Interactive work stays lightweight; completion marking is strict.
#
# Verifies (ALL required — any failure is fail-closed, ROADMAP left byte-identical):
#   1. target heading present verbatim in docs/ROADMAP.md
#   2. evaluator PASS evidence: .claude/.phase-grade has run_id == HEAD and verdict == PASS
#   3. fresh test evidence: .claude/.tick-evidence.json (from scripts/test-evidence.sh) is valid
#      JSON with run_id == HEAD AND (passed == true, OR passed == null with grade no_tests_ok=1)
#   4. secret scan of the phase diff is clean
#   5. high-stakes paths NOT touched (path match; content match added in Phase 2B)
#   6. the target phase still has an open "- [ ]" item
#   7. after ticking, the open-item count strictly dropped
#
# Side effects: ticks ROADMAP. (Phase 2B adds: update the docs/STATE.md machine block.)
# Does NOT commit, push, open a PR, run the evaluator, or archive — the CALLER owns those.
#
# Usage: bash scripts/tick.sh ["<exact phase heading>"] [--supervised-approved] [--note "<why>"]
#        (heading defaults to .claude/.phase-ready). A "Mode: supervised" phase ticks ONLY with an
#        explicit human --supervised-approved (recorded, HEAD-bound, in .claude/.supervised-approval);
#        this clears the supervised refusal alone and relaxes no other gate.
# Exit:  0 = ticked · 1 = refused (stop) · 3 = high-stakes / unapproved-supervised (caller must NOT push)
set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)" || exit 1

ROADMAP="docs/ROADMAP.md"
GRADE=".claude/.phase-grade"
EVIDENCE=".claude/.tick-evidence.json"

refuse() {
  echo "tick: REFUSED — $1" >&2
  printf 'tick refused: %s\n' "$1" > NEXT_FINDINGS.md 2>/dev/null || true
  exit 1
}

# render_state <ticked-heading> <ticked-roadmap-file> <current-state-file> <out-file>: PURELY GENERATE
# the new docs/STATE.md content into <out-file>, WITHOUT modifying the current state. It rewrites the
# machine-managed block (between the markers) with the last ticked phase + the next open phase (read
# from the already-ticked roadmap temp), leaving the model's narrative OUTSIDE the markers untouched;
# if the markers are absent, the block is appended once. Returns 0 on success, non-zero if generation
# failed. The caller (the F4 two-file transaction below) validates + applies it atomically-or-rolls-back
# — so a failed STATE update never leaves ROADMAP ticked with STATE stale (finding N-2 + F4).
STATE_BEGIN='<!-- lean:auto:begin -->'
STATE_END='<!-- lean:auto:end -->'
render_state() {
  local ticked="$1" rmap="$2" state="$3" out="$4"
  local stamp next_h next_t blockfile rc=0
  [ -r "$state" ] || return 1   # can't read the current STATE → fail cleanly (never silently drop prose)
  stamp=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "unknown")
  # First "## " heading that still has an open "- [ ]" item in the NEW (ticked) roadmap, and its text.
  next_h=$(awk '/^## /{h=$0} /- \[ \]/ && h!=""{print h; exit}' "$rmap")
  next_t=$(awk '/^## /{h=$0} /- \[ \]/ && h!=""{sub(/^[[:space:]]*- \[ \] /,""); print; exit}' "$rmap")
  blockfile=$(mktemp 2>/dev/null || echo "$out.block.$$")
  {
    echo "$STATE_BEGIN"
    echo "_Auto-generated by scripts/tick.sh on each roadmap tick — do not edit between these markers._"
    echo ""
    echo "- Last ticked: ${ticked#\#\# }"
    echo "- Updated: ${stamp}"
    if [ -n "$next_h" ]; then
      echo "- Next phase: ${next_h#\#\# }"
      echo "- Next action: ${next_t:-<see roadmap>}"
    else
      echo "- Roadmap complete — every phase is ticked. Close it with scripts/close-milestone.sh (or the milestone skill)."
    fi
    echo "$STATE_END"
  } > "$blockfile" || rc=1
  if [ "$rc" = 0 ]; then
    if grep -qF "$STATE_BEGIN" "$state"; then
      awk -v b="$STATE_BEGIN" -v e="$STATE_END" -v bf="$blockfile" '
        BEGIN { while ((getline l < bf) > 0) blk = blk l "\n" }
        $0==b { printf "%s", blk; skip=1; next }
        $0==e { if (skip) { skip=0; next } }
        !skip { print }
      ' "$state" > "$out" 2>/dev/null || rc=1
    else
      { cat "$state"; echo ""; cat "$blockfile"; } > "$out" 2>/dev/null || rc=1
    fi
  fi
  rm -f "$blockfile" 2>/dev/null || true
  return "$rc"
}

APPROVAL=".claude/.supervised-approval"
# supervised_approval_valid <heading>: the gate for a "Mode: supervised" phase. Returns 0 (valid) iff
# a human explicitly approved THIS phase at THIS commit. It is NOT a bypass of any other gate — the
# grade, evidence, secret, gate-config and high-stakes checks all run ABOVE the supervised block and
# exit before it, so a valid approval only clears the supervised-mode refusal, nothing else. Two ways
# to be valid:
#   • --supervised-approved passed on THIS run → WRITE the approval file (same key=value shape as
#     .phase-grade), binding it to HEAD + the exact heading + a UTC stamp + the optional --note, then
#     accept and fall through to the normal open-item + count-drop tick.
#   • else → READ .claude/.supervised-approval and accept ONLY if it is well-formed AND title == the
#     heading being ticked AND run_id == HEAD (same freshness idiom as the grade check: a new commit
#     makes a prior approval stale). Missing / malformed / title-mismatch / stale → invalid (fail closed).
supervised_approval_valid() {
  local h="$1"
  if [ "$SUPERVISED_APPROVED" -eq 1 ]; then
    mkdir -p .claude
    {
      echo "run_id=$HEAD"
      echo "title=$h"
      echo "approved_at=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)"
      echo "note=$APPROVAL_NOTE"
    } > "$APPROVAL"
    return 0
  fi
  [ -f "$APPROVAL" ] || return 1
  local a_run a_title
  a_run=$(grep -E '^run_id=' "$APPROVAL" | head -1 | cut -d= -f2- || true)
  a_title=$(grep -E '^title=' "$APPROVAL" | head -1 | cut -d= -f2- || true)
  [ -n "$a_run" ] || return 1
  [ "$a_title" = "$h" ] || return 1
  [ "$a_run" = "$HEAD" ] || return 1
  return 0
}

# --- 1. args: an optional positional heading + supervised-approval flags (loop mirrors close-milestone.sh) ---
SUPERVISED_APPROVED=0
APPROVAL_NOTE=""
heading=""
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      echo "usage: tick.sh [\"<exact phase heading>\"] [--supervised-approved] [--note \"<why>\"]"
      echo "  The single roadmap-completion gate: ticks ONLY on a recorded evaluator PASS + fresh green"
      echo "  test evidence bound to HEAD + a clean secret scan + no high-stakes changes. A phase marked"
      echo "  'Mode: supervised' ALSO needs --supervised-approved, which records an auditable, HEAD-bound"
      echo "  approval in .claude/.supervised-approval (it does NOT relax any other gate). Heading defaults"
      echo "  to .claude/.phase-ready. Exit: 0 ticked, 1 refused, 3 high-stakes/supervised. Env TICK_BASE"
      echo "  (trusted) overrides .claude/.phase-base."
      exit 0 ;;
    --supervised-approved) SUPERVISED_APPROVED=1; shift ;;
    --note) shift; APPROVAL_NOTE="${1:-}"; [ $# -gt 0 ] && shift ;;
    -*) echo "tick: unknown option '$1' (try -h)" >&2; exit 1 ;;
    *) [ -z "$heading" ] && heading="$1"; shift ;;
  esac
done
[ -z "$heading" ] && heading=$(cat .claude/.phase-ready 2>/dev/null || true)
[ -z "$heading" ] && refuse "no phase heading (pass one, or write .claude/.phase-ready)"
[ -f "$ROADMAP" ] || refuse "missing $ROADMAP"
# Exact FULL-LINE match (-x): every downstream awk block consumes the heading via `$0==ph`, so a
# mere substring that isn't a standalone `## ` line would pass here yet match nothing later. Make
# the existence check agree with the consumption — refuse loudly instead of failing silently.
grep -qxF -e "$heading" "$ROADMAP" || refuse "phase heading not found as an exact line in roadmap: '$heading'"

HEAD=$(git rev-parse HEAD 2>/dev/null) || refuse "not a git repo / no HEAD"
command -v jq >/dev/null 2>&1 || refuse "jq required to read evidence"

# --- leftover-transaction-artifact guard (F4) ---
# The completion transition below writes *.tick-tmp / *.tick-bak next to ROADMAP/STATE and cleans them
# on success. Their presence NOW means a prior run was interrupted mid-transition — do NOT guess which
# file is authoritative; stop and let the human inspect. (docs/ROADMAP.md is authoritative; a *.tick-bak
# is the pre-tick original.)
LEFTOVER_TX=$(ls docs/ROADMAP.md.tick-tmp docs/ROADMAP.md.tick-bak docs/STATE.md.tick-tmp docs/STATE.md.tick-bak 2>/dev/null || true)
if [ -n "$LEFTOVER_TX" ]; then
  echo "tick: ⛔ leftover completion-transaction artifacts from an interrupted prior run:" >&2
  printf '%s\n' "$LEFTOVER_TX" | sed 's/^/    /' >&2
  echo "tick:    docs/ROADMAP.md is authoritative; a *.tick-bak is the pre-tick original. Inspect, then" >&2
  echo "tick:    restore the intended file and delete the *.tick-tmp/*.tick-bak artifacts before re-running." >&2
  refuse "interrupted completion transaction — resolve the *.tick-* artifacts first (fail-closed)"
fi

# --- clean-tree gate (H5) ---
# Exact-HEAD evidence (grade + test run_id both == HEAD) is only an HONEST description of what was
# judged when the checkout EQUALS HEAD. The secret + high-stakes scans read BASE..HEAD, which is
# committed-only — an uncommitted secret or high-stakes change sitting in the working tree is
# invisible to them, yet the phase would be ticked as if the checkout were the judged revision.
# Refuse a dirty tree BEFORE mutating ROADMAP/STATE. `git status --porcelain` already excludes
# gitignored files, which is EXACTLY the runtime-artifact exemption we want (.claude/.phase-grade,
# .tick-evidence.json, .phase-base, .phase-ready, .supervised-approval, NEXT_FINDINGS.md,
# autopilot.log, ... — all gitignored by the scaffold). Do NOT add --ignored. ROADMAP/STATE are
# tick's OWN later output; at this point they still equal HEAD, so they never trip this.
# (v2.7.0's record-grade.sh already refuses a dirty TRACKED tree at grade time; this is stronger —
# it also catches untracked non-ignored files, e.g. a leaked secret file — and closes the
# grade→tick window on the manual /wrap path, which has no orchestrator to re-check.)
DIRTY=$(git status --porcelain 2>/dev/null)
if [ -n "$DIRTY" ]; then
  echo "tick: REFUSED — working tree not clean; exact-HEAD evidence requires the checkout to equal HEAD:" >&2
  printf '%s\n' "$DIRTY" | sed 's/^/    /' >&2
  refuse "uncommitted changes present (commit or stash them, then re-run)"
fi

# --- 2. evaluator PASS evidence ---
[ -f "$GRADE" ] || refuse "missing evaluator grade evidence ($GRADE) — run the evaluator first"
g_run=$(grep -E '^run_id=' "$GRADE" | head -1 | cut -d= -f2- || true)
g_verdict=$(grep -E '^verdict=' "$GRADE" | head -1 | cut -d= -f2- || true)
g_notests=$(grep -E '^no_tests_ok=' "$GRADE" | head -1 | cut -d= -f2- || true)
[ "$g_run" = "$HEAD" ] || refuse "grade evidence is stale (grade run_id '$g_run' != HEAD '$HEAD')"
[ "$g_verdict" = "PASS" ] || refuse "evaluator verdict is not PASS (got '$g_verdict')"

# --- 3. fresh test evidence ---
[ -f "$EVIDENCE" ] || refuse "missing test evidence ($EVIDENCE) — run scripts/test-evidence.sh"
# `jq empty` was observed to be a no-op on some bundled jq builds (audit M4 — same as doctor.sh):
# it accepts malformed input, so the run_id bind below is the only thing catching bad JSON. Use
# `jq -e 'type'` instead — it emits the value's type and sets a non-zero exit on unparseable input
# (`type` always yields a non-null/non-false string on valid JSON, so this never false-rejects).
jq -e 'type' "$EVIDENCE" >/dev/null 2>&1 || refuse "test evidence is not valid JSON"
e_run=$(jq -r '.run_id // ""' "$EVIDENCE")
e_passed=$(jq -r '.passed' "$EVIDENCE" 2>/dev/null || echo "missing")
[ "$e_run" = "$HEAD" ] || refuse "test evidence is stale (evidence run_id '$e_run' != HEAD '$HEAD')"
case "$e_passed" in
  true) : ;;
  null)
    [ "$g_notests" = "1" ] \
      || refuse "no test suite (passed:null) and the evaluator did not confirm NO_TESTS_OK" ;;
  *) refuse "tests are not green (passed=$e_passed)" ;;
esac

# --- 4 & 5. secret + high-stakes over the WHOLE phase diff ---
# Phase scan floor. The gates below run over BASE..HEAD; a BASE that is forged, empty, or == HEAD
# would silently NARROW (or empty) the secret + high-stakes window, hiding a malicious commit.
# Precedence:
#   • TICK_BASE env SET → the orchestrator (headless scripts/autopilot.sh) derived this base in its
#     OWN trusted shell, OUTSIDE the --dangerously-skip-permissions builder. Use it and NEVER fall
#     back to the builder-writable file: a bad trusted env must fail closed, not silently degrade to
#     the untrusted .claude/.phase-base (which a compromised builder can forge to HEAD to empty the
#     scan). autopilot also overwrites .phase-base with this same trusted value before the evaluator.
#   • TICK_BASE ABSENT → the in-session /wrap path; read the builder-written .claude/.phase-base.
# Both sources are strict-ancestor-validated below. That stops a base from being emptied (== HEAD),
# pointed at unrelated history, or set to a non-commit. It does NOT establish that the base is the
# ORIGINAL phase start: a builder can advance .claude/.phase-base to a LATER ancestor B (still a
# strict ancestor of HEAD), narrowing A..HEAD to B..HEAD and hiding the commits between A and B
# (finding H1). The TICK_BASE path is safe because the orchestrator derives the base OUTSIDE the
# builder; the manual .phase-base path is human-reviewed, not builder-proof, until scripts/start-phase.sh
# anchors it (planned). Do NOT read this comment as "a forged file cannot narrow the scan" — it can.
ANCHOR_USED=0
if [ -n "${TICK_BASE+set}" ]; then
  BASE="$TICK_BASE"
  BASE_SRC="TICK_BASE env (orchestrator-trusted)"
  [ -n "$BASE" ] || refuse "TICK_BASE is set but empty — a trusted base must be a real commit (fail-closed)"
elif [ -f .claude/.phase-anchor ]; then
  ANCHOR_USED=1
  # Manual mode, NEW mechanism (H1): prefer the TRACKED, tamper-evident anchor authored by
  # scripts/start-phase.sh over the gitignored, builder-writable .phase-base. The anchor's base lives
  # in committed git history, so advancing it is a VISIBLE commit inside the judged range — not the
  # silent ignored-file rewrite the old .phase-base allowed. (Still not builder-PROOF — that needs the
  # orchestrator's out-of-builder shell, i.e. headless TICK_BASE — but it is tamper-evident + reviewed.)
  BASE=$(grep -E '^base=' .claude/.phase-anchor 2>/dev/null | head -1 | cut -d= -f2-)
  BASE_SRC=".claude/.phase-anchor (start-phase.sh)"
  [ -n "$BASE" ] || refuse "no base= in .claude/.phase-anchor — re-run scripts/start-phase.sh (fail-closed)"
else
  BASE=$(cat .claude/.phase-base 2>/dev/null || true)
  BASE_SRC=".claude/.phase-base"
  [ -n "$BASE" ] || refuse "no phase start recorded — run scripts/start-phase.sh first (fail-closed)"
fi
# Strict-ancestor guard (ALL sources): resolve to a real commit, require it is NOT HEAD (which would
# make BASE..HEAD empty) and IS a genuine ancestor of HEAD (not unrelated history). Any failure is
# fail-closed — a forged base can neither narrow the scan to nothing nor point it at the wrong commits.
BASE_SHA=$(git rev-parse --verify --quiet "${BASE}^{commit}" 2>/dev/null || true)
[ -n "$BASE_SHA" ] || refuse "phase base ($BASE_SRC = '$BASE') is not a resolvable commit (fail-closed)"
[ "$BASE_SHA" != "$HEAD" ] || refuse "phase base ($BASE_SRC) equals HEAD — the scan window would be empty (fail-closed)"
git merge-base --is-ancestor "$BASE_SHA" "$HEAD" 2>/dev/null \
  || refuse "phase base ($BASE_SRC = '$BASE') is not an ancestor of HEAD (fail-closed)"
RANGE="${BASE_SHA}..HEAD"
# Print the exact judged range (C-C): in manual mode the human on the loop is the trusted reviewer, so
# make the window they are vouching for explicit rather than implicit.
echo "tick: judging range ${BASE_SHA:0:12}..${HEAD:0:12}  (base source: $BASE_SRC)" >&2

# --- anchor base-integrity (F3b / audit I1) ---
# The strict-ancestor guard above stops an EMPTY or unrelated base, but not NARROWING: a builder could
# advance the anchor's base= to a later ancestor and commit it (visible, but the old code still ticked).
# The anchor is authored by scripts/start-phase.sh as a commit whose PARENT is exactly the recorded
# base. So require: the commit that LAST modified .claude/.phase-anchor has base= as its first parent.
# A naive base rewrite ('base=<later ancestor>' + an ordinary commit) then fails closed — that commit's
# parent is the previous HEAD, not the new base. HONEST residual (documented): a builder that runs
# arbitrary git can still `reset --hard` + re-anchor to reconstruct history; no local, crypto-free check
# prevents that — which is exactly why HEADLESS derives the base OUTSIDE the builder (TICK_BASE). This
# raises the manual bar from tamper-EVIDENT to "the naive narrowing is REFUSED".
if [ "$ANCHOR_USED" = 1 ]; then
  a_commit=$(git log -1 --format=%H -- .claude/.phase-anchor 2>/dev/null || true)
  if [ -n "$a_commit" ]; then
    a_parent=$(git rev-parse --verify --quiet "${a_commit}^" 2>/dev/null || true)
    if [ -n "$a_parent" ] && [ "$a_parent" != "$BASE_SHA" ]; then
      echo "tick: ⛔ .claude/.phase-anchor base does not match the commit that set it —" >&2
      echo "tick:    anchor base=${BASE_SHA:0:12} but the anchor-setting commit ${a_commit:0:12} has parent ${a_parent:0:12}." >&2
      echo "tick:    This is how a narrowed scan window looks (the base was advanced). Re-run scripts/start-phase.sh" >&2
      echo "tick:    from the true phase start on a clean tree, or review the range manually. NOT ticking." >&2
      exit 3
    fi
  fi
fi

[ -f .claude/lib/_secret-scan.sh ] && . .claude/lib/_secret-scan.sh 2>/dev/null || true
[ -f .claude/lib/_high-stakes.sh ] && . .claude/lib/_high-stakes.sh 2>/dev/null || true
[ -f .claude/lib/_roadmap.sh ]     && . .claude/lib/_roadmap.sh     2>/dev/null || true
[ -f .claude/lib/_test-cmd.sh ]    && . .claude/lib/_test-cmd.sh    2>/dev/null || true

command -v secret_scan_diff   >/dev/null 2>&1 || refuse "secret-scan library unavailable — fail-closed"
command -v high_stakes_match  >/dev/null 2>&1 || refuse "high-stakes library unavailable — fail-closed"
command -v roadmap_phase_mode >/dev/null 2>&1 || refuse "roadmap parser library unavailable — fail-closed"

# --- manual test-command identity binding (F3a / audit H2/M3) ---
# In MANUAL mode (no orchestrator gate-control byte-check), a builder could commit a change to
# .claude/test-command mid-phase to swap the graded suite for a weaker one, then generate green
# evidence with it. The phase-start anchor records the authorized command identity; require the anchor,
# the recorded evidence, and the CURRENT authorized command to all agree before ticking. Only meaningful
# when the anchor is the base source (manual mode) AND the phase actually produced a green test command
# (a no-tests phase, passed:null, carries no command to bind). Headless is unaffected: it gate-controls
# .claude/test-command against START_REF, and LEAN_TEST_CMD is set in the orchestrator's own shell.
if [ "$ANCHOR_USED" = 1 ] && [ "$e_passed" = "true" ] && command -v authorized_test_cmd >/dev/null 2>&1; then
  an_cmd=$(grep -E '^test_command=' .claude/.phase-anchor 2>/dev/null | head -1 | cut -d= -f2-)
  an_sha=$(grep -E '^test_config_sha=' .claude/.phase-anchor 2>/dev/null | head -1 | cut -d= -f2-)
  ev_cmd=$(jq -r '.command // ""' "$EVIDENCE" 2>/dev/null)
  cur_cmd=$(authorized_test_cmd 2>/dev/null || true)
  cur_src=$(authorized_test_cmd_source 2>/dev/null || echo none)
  # Only enforce when the anchor actually bound a command (older/no-command anchors carry an empty
  # test_command — documented residual: a phase started with no authorized command is not bound).
  if [ -n "$an_cmd" ]; then
    if [ "$an_cmd" != "$ev_cmd" ]; then
      refuse "graded test command ('$ev_cmd') differs from the phase-start authorized command ('$an_cmd') — the suite was changed mid-phase. Re-run scripts/start-phase.sh from a clean tree if the change is intentional."
    fi
    if [ "$an_cmd" != "$cur_cmd" ]; then
      refuse "the currently-authorized test command ('$cur_cmd') differs from the phase-start command ('$an_cmd') — .claude/test-command (or LEAN_TEST_CMD) changed mid-phase. Re-run scripts/start-phase.sh if intentional."
    fi
    # Stronger content bind for the file source, when the anchor recorded a sha (new anchors).
    if [ -n "$an_sha" ] && [ "$cur_src" = "file:.claude/test-command" ]; then
      cur_sha=$(authorized_test_cmd_config_sha 2>/dev/null || true)
      if [ -n "$cur_sha" ] && [ "$an_sha" != "$cur_sha" ]; then
        refuse ".claude/test-command CONTENT changed since phase start (config sha ${an_sha:0:12} → ${cur_sha:0:12}) — re-run scripts/start-phase.sh if intentional."
      fi
    fi
  fi
fi

SF=$(secret_scan_diff "$RANGE"); SRC=$?
if [ "$SRC" -ne 0 ]; then
  echo "tick: REFUSED — secret(s) in phase diff ($RANGE):" >&2
  printf '%s\n' "$SF" | sed 's/^/    /' >&2
  printf 'tick refused: secret in phase diff\n%s\n' "$SF" > NEXT_FINDINGS.md 2>/dev/null || true
  exit 1
fi

CHANGED=$(git diff --name-only "$RANGE" 2>/dev/null || true)
# The high-stakes gate's OWN control files are themselves high-stakes. If this phase edits the
# path allowlist or the matcher library, it could self-exempt (add its own allowlist line) or
# self-narrow (shrink HIGH_STAKES_RE) the very gate tick.sh then reads — invisible to the keyword
# match, since neither path is itself in HIGH_STAKES_RE. Force supervised review (exit 3, same as a
# high-stakes hit) whenever either appears in the phase diff, regardless of the new contents, so
# unattended autopilot can never remove its own supervision. Exact FULL-LINE match (-xF) so a
# sibling like `_high-stakes.sh.bak` never trips it.
GATE_CFG=$(printf '%s\n' "$CHANGED" | grep -xF -e '.claude/high-stakes-path-allowlist' -e '.claude/lib/_high-stakes.sh' || true)
if [ -n "$GATE_CFG" ]; then
  echo "tick: ⛔ HIGH-STAKES gate config changed — supervised review required, NOT ticking:" >&2
  printf '%s\n' "$GATE_CFG" | sed 's/^/    /' >&2
  exit 3
fi
# Three-state, NOT `if HS=$(...)`: high_stakes_match returns 0 matched / 1 clean / 2 config error.
# A plain `if` command-substitution would swallow rc 2 exactly like rc 1 (finding N-4) — a typo in
# the ENFORCED HIGH_STAKES_RE would then silently fall through as "no high-stakes paths" and auto-tick.
# rc 2 must fail closed, same as a missing library above.
HS=$(high_stakes_match "$CHANGED"); hs_rc=$?
case "$hs_rc" in
  0) echo "tick: ⛔ HIGH-STAKES paths changed — supervised review required, NOT ticking:" >&2
     printf '%s\n' "$HS" | sed 's/^/    /' >&2
     exit 3 ;;
  1) : ;;   # clean
  *) refuse "high-stakes path matcher configuration error (rc=$hs_rc) — fail-closed (fix HIGH_STAKES_RE)" ;;
esac
# Content-level high-stakes: destructive operations in a benignly-named file. Scan the
# ADDED lines of the whole phase diff. A hit forces supervised review (exit 3), same as a path.
if command -v high_stakes_content_match >/dev/null 2>&1; then
  ADDED=$(git diff "$RANGE" --unified=0 2>/dev/null | grep -E '^\+' | grep -Ev '^\+\+\+' || true)
  HC=$(high_stakes_content_match "$ADDED"); hc_rc=$?
  case "$hc_rc" in
    0) echo "tick: ⛔ HIGH-STAKES content in phase diff — supervised review required, NOT ticking:" >&2
       printf '%s\n' "$HC" | sed 's/^/    /' >&2
       exit 3 ;;
    1) : ;;   # clean
    *) refuse "high-stakes content matcher configuration error (rc=$hc_rc) — fail-closed" ;;
  esac
fi

# Mode: supervised — the author flagged this phase as human-on-the-loop. Enforce it (the tag
# used to be advisory/unparsed): refuse to auto-tick, same supervised exit as a high-stakes hit.
# Parse via the SHARED fail-closed parser (_roadmap.sh): rc 2 (duplicate/invalid Mode) is a hard
# refuse — a phase with two Mode: lines, or `Mode: superviced`, must never be waved through as
# "not supervised". An ABSENT Mode line (rc 0 + empty) stays loopable, preserving legacy behavior
# (a phase without a Mode line still ticks; only autopilot's unattended pre-build gate refuses it).
PHASE_MODE=$(roadmap_phase_mode "$ROADMAP" "$heading"); pm_rc=$?
[ "$pm_rc" = 2 ] && refuse "phase Mode: is duplicate or invalid — fail-closed (fix the Mode: line in $ROADMAP)"
case "$PHASE_MODE" in
  supervised)
    # Everything above (grade, evidence, secret, gate-config, high-stakes path+content) has already
    # run and would have exited before reaching here — so this approval clears ONLY the supervised
    # refusal, never any other gate. Valid approval → fall through to the open-item + tick logic below.
    if supervised_approval_valid "$heading"; then
      echo "tick: 'Mode: supervised' phase has a valid human approval bound to HEAD — proceeding." >&2
    else
      echo "tick: ⛔ phase is marked 'Mode: supervised' — human review required, NOT auto-ticking." >&2
      echo "tick:    to approve THIS phase at THIS commit, a human runs:" >&2
      echo "tick:      bash scripts/tick.sh --supervised-approved \"$heading\" --note \"<why it's safe>\"" >&2
      exit 3
    fi ;;
esac

# --- 6. target phase still has an open item ---
open_in_phase=$(PH="$heading" awk '
  $0==ENVIRON["PH"] {inphase=1; next}
  /^## / && inphase {inphase=0}
  inphase && /- \[ \]/ {c++}
  END {print c+0}
' "$ROADMAP")
[ "${open_in_phase:-0}" -gt 0 ] || refuse "no open '- [ ]' items under '$heading' (already ticked?)"

# --- 7. rollback-safe two-file completion transition (F4) ---
# Generate BOTH new files COMPLETELY, validate them, back up the originals, apply BOTH, and roll back
# on any failure — so a completion always ends with ROADMAP+STATE both updated, or both at their pre-tick
# state, never half-applied. `✓ ticked` prints ONLY after both replacements succeed and verify. (The old
# order mutated ROADMAP in place, then STATE; a STATE failure left ROADMAP ticked with STATE stale — N-2.
# A full doctor --state cross-file repair engine is deliberately deferred; this is the minimal safe core.)
STATE="docs/STATE.md"
R_TMP="$ROADMAP.tick-tmp"; R_BAK="$ROADMAP.tick-bak"
S_TMP="$STATE.tick-tmp";   S_BAK="$STATE.tick-bak"
tx_temps() { rm -f "$R_TMP" "$S_TMP" 2>/dev/null || true; }

# (1) generate the ticked ROADMAP into a temp (pure — the real file is untouched).
before=$(grep -c '\- \[ \]' "$ROADMAP" 2>/dev/null)
if ! PH="$heading" awk '
  $0==ENVIRON["PH"] {inphase=1; print; next}
  /^## / && inphase {inphase=0}
  inphase {gsub(/- \[ \]/, "- [x]")}
  {print}
' "$ROADMAP" > "$R_TMP" 2>/dev/null; then
  tx_temps; refuse "could not generate the updated ROADMAP (write failed) — nothing changed."
fi

# (2) generate the new STATE into a temp (pure). If there is no STATE file, there is nothing to update
# (legacy behavior). Read the NEXT phase from the ticked roadmap temp, not the on-disk (unticked) one.
STATE_MODE=update
if [ ! -f "$STATE" ]; then
  STATE_MODE=skip
elif ! render_state "$heading" "$R_TMP" "$STATE" "$S_TMP"; then
  tx_temps; refuse "could not generate the updated docs/STATE.md — nothing changed (ROADMAP not ticked)."
fi

# (2b) validate both temps BEFORE touching anything: ROADMAP open-count strictly dropped; STATE has a
# well-formed auto-block; and the real targets are actually WRITABLE (a read-only docs/STATE.md must
# fail here, cleanly, NOT half-apply — finding N-2, now caught before any mutation).
after=$(grep -c '\- \[ \]' "$R_TMP" 2>/dev/null)
if [ "${after:-0}" -ge "${before:-0}" ]; then
  tx_temps; refuse "tick changed no items under '$heading' (roadmap left unchanged)."
fi
[ -w "$ROADMAP" ] || { tx_temps; refuse "docs/ROADMAP.md is not writable — cannot tick (make it writable, then re-run)."; }
if [ "$STATE_MODE" = update ]; then
  grep -qF "$STATE_BEGIN" "$S_TMP" 2>/dev/null || { tx_temps; refuse "generated STATE is missing its auto-block markers — refusing (nothing changed)."; }
  [ -w "$STATE" ] || { tx_temps; refuse "docs/STATE.md is not writable — cannot update it (make it writable, then re-run; nothing changed)."; }
fi

# (3) back up the originals.
cp "$ROADMAP" "$R_BAK" 2>/dev/null || { tx_temps; refuse "could not back up $ROADMAP — nothing changed."; }
if [ "$STATE_MODE" = update ]; then
  cp "$STATE" "$S_BAK" 2>/dev/null || { rm -f "$R_BAK"; tx_temps; refuse "could not back up docs/STATE.md — nothing changed."; }
fi

# tx_restore: put both originals back from their backups (best effort). Prints a warning per file that
# could not be restored so the caller can preserve the backups + print manual recovery.
tx_restore() {
  local ok=0
  cp "$R_BAK" "$ROADMAP" 2>/dev/null || ok=1
  [ "$STATE_MODE" = update ] && { cp "$S_BAK" "$STATE" 2>/dev/null || ok=1; }
  return "$ok"
}

# (4) apply BOTH. (5) on any failure, roll BOTH back.
apply_ok=1
mv "$R_TMP" "$ROADMAP" 2>/dev/null || apply_ok=0
if [ "$apply_ok" = 1 ] && [ "$STATE_MODE" = update ]; then
  mv "$S_TMP" "$STATE" 2>/dev/null || apply_ok=0
fi
if [ "$apply_ok" != 1 ]; then
  if tx_restore; then
    rm -f "$R_BAK" "$S_BAK"; tx_temps
    refuse "completion transition FAILED (a file replacement errored) — docs/ROADMAP.md and docs/STATE.md were rolled back to their pre-tick state. Fix the cause and re-run on a clean tree."
  fi
  # Rollback itself failed → preserve the backups and print exact manual recovery (fail-closed).
  echo "tick: ⛔ completion FAILED and automatic rollback could not fully restore the originals." >&2
  echo "tick:    The pre-tick originals are PRESERVED as backups — restore them by hand, then re-run:" >&2
  echo "tick:      cp \"$R_BAK\" \"$ROADMAP\"" >&2
  [ "$STATE_MODE" = update ] && echo "tick:      cp \"$S_BAK\" \"$STATE\"" >&2
  tx_temps
  exit 1
fi

# (6) verify the resulting cross-file state before reporting success.
new_after=$(grep -c '\- \[ \]' "$ROADMAP" 2>/dev/null)
verify_ok=1
[ "${new_after:-0}" -lt "${before:-0}" ] || verify_ok=0
if [ "$STATE_MODE" = update ]; then
  grep -qF "Last ticked: ${heading#\#\# }" "$STATE" 2>/dev/null || verify_ok=0
fi
if [ "$verify_ok" != 1 ]; then
  tx_restore || true
  rm -f "$R_BAK" "$S_BAK"; tx_temps
  refuse "post-tick cross-file verification failed — rolled back (the ROADMAP tick and STATE update did not both land)."
fi

# (7) success → clean temps + backups, drop the consumed runtime evidence, report.
rm -f "$R_BAK" "$S_BAK"; tx_temps
rm -f .claude/.phase-ready .claude/.phase-grade .claude/.supervised-approval 2>/dev/null || true
echo "tick: ✓ ticked '$heading' ($((before - new_after)) item(s))"
exit 0
